if(SKEPU_MPI AND SKEPU_CUDA)
	set(SKEPU_MPI_CUDA ON)
else()
	set(SKEPU_MPI_CUDA OFF)
endif()

option(SKEPU_EXAMPLE_CELLULAR_AUTOMATON "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_CELLULAR_AUTOMATON_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_CELLULAR_AUTOMATON_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_CELLULAR_AUTOMATON_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_CELLULAR_AUTOMATON_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_CELLULAR_AUTOMATON_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_CELLULAR_AUTOMATON
	SKEPU_EXAMPLE_CELLULAR_AUTOMATON_CUDA
	SKEPU_EXAMPLE_CELLULAR_AUTOMATON_MPI
	SKEPU_EXAMPLE_CELLULAR_AUTOMATON_MPI_CUDA
	SKEPU_EXAMPLE_CELLULAR_AUTOMATON_OPENCL
	SKEPU_EXAMPLE_CELLULAR_AUTOMATON_OPENMP)

option(SKEPU_EXAMPLE_CMA "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_CMA_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_CMA_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_CMA_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_CMA_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_CMA_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_CMA
	SKEPU_EXAMPLE_CMA_CUDA
	SKEPU_EXAMPLE_CMA_MPI
	SKEPU_EXAMPLE_CMA_MPI_CUDA
	SKEPU_EXAMPLE_CMA_OPENCL
	SKEPU_EXAMPLE_CMA_OPENMP)

option(SKEPU_EXAMPLE_COULOMBIC "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_COULOMBIC_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_COULOMBIC_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_COULOMBIC_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_COULOMBIC_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_COULOMBIC_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_COULOMBIC
	SKEPU_EXAMPLE_COULOMBIC_CUDA
	SKEPU_EXAMPLE_COULOMBIC_MPI
	SKEPU_EXAMPLE_COULOMBIC_MPI_CUDA
	SKEPU_EXAMPLE_COULOMBIC_OPENCL
	SKEPU_EXAMPLE_COULOMBIC_OPENMP)

option(SKEPU_EXAMPLE_DOTPRODUCT "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_DOTPRODUCT_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_DOTPRODUCT_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_DOTPRODUCT_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_DOTPRODUCT_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_DOTPRODUCT_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_DOTPRODUCT
	SKEPU_EXAMPLE_DOTPRODUCT_CUDA
	SKEPU_EXAMPLE_DOTPRODUCT_MPI
	SKEPU_EXAMPLE_DOTPRODUCT_MPI_CUDA
	SKEPU_EXAMPLE_DOTPRODUCT_OPENCL
	SKEPU_EXAMPLE_DOTPRODUCT_OPENMP)

option(SKEPU_EXAMPLE_EDGEDETECT "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_EDGEDETECT_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_EDGEDETECT_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_EDGEDETECT_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_EDGEDETECT_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_EDGEDETECT_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_EDGEDETECT
	SKEPU_EXAMPLE_EDGEDETECT_CUDA
	SKEPU_EXAMPLE_EDGEDETECT_MPI
	SKEPU_EXAMPLE_EDGEDETECT_MPI_CUDA
	SKEPU_EXAMPLE_EDGEDETECT_OPENCL
	SKEPU_EXAMPLE_EDGEDETECT_OPENMP)

option(SKEPU_EXAMPLE_HEAT_DIFFUSION "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_HEAT_DIFFUSION_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_HEAT_DIFFUSION_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_HEAT_DIFFUSION_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_HEAT_DIFFUSION_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_HEAT_DIFFUSION_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_HEAT_DIFFUSION
	SKEPU_EXAMPLE_HEAT_DIFFUSION_CUDA
	SKEPU_EXAMPLE_HEAT_DIFFUSION_MPI
	SKEPU_EXAMPLE_HEAT_DIFFUSION_MPI_CUDA
	SKEPU_EXAMPLE_HEAT_DIFFUSION_OPENCL
	SKEPU_EXAMPLE_HEAT_DIFFUSION_OPENMP)

option(SKEPU_EXAMPLE_MANDELBROT "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MANDELBROT_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MANDELBROT_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MANDELBROT_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MANDELBROT_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MANDELBROT_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MANDELBROT
	SKEPU_EXAMPLE_MANDELBROT_CUDA
	SKEPU_EXAMPLE_MANDELBROT_MPI
	SKEPU_EXAMPLE_MANDELBROT_MPI_CUDA
	SKEPU_EXAMPLE_MANDELBROT_OPENCL
	SKEPU_EXAMPLE_MANDELBROT_OPENMP)

option(SKEPU_EXAMPLE_MAXMIN "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MAXMIN_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MAXMIN_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MAXMIN_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MAXMIN_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MAXMIN_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MAXMIN
	SKEPU_EXAMPLE_MAXMIN_CUDA
	SKEPU_EXAMPLE_MAXMIN_MPI
	SKEPU_EXAMPLE_MAXMIN_MPI_CUDA
	SKEPU_EXAMPLE_MAXMIN_OPENCL
	SKEPU_EXAMPLE_MAXMIN_OPENMP)

option(SKEPU_EXAMPLE_MEDIAN "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MEDIAN_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MEDIAN_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MEDIAN_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MEDIAN_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MEDIAN_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MEDIAN
	SKEPU_EXAMPLE_MEDIAN_CUDA
	SKEPU_EXAMPLE_MEDIAN_MPI
	SKEPU_EXAMPLE_MEDIAN_MPI_CUDA
	SKEPU_EXAMPLE_MEDIAN_OPENCL
	SKEPU_EXAMPLE_MEDIAN_OPENMP)
	
option(SKEPU_EXAMPLE_MILLER_RABIN "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MILLER_RABIN_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MILLER_RABIN_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MILLER_RABIN_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MILLER_RABIN_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MILLER_RABIN_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MILLER_RABIN
	SKEPU_EXAMPLE_MILLER_RABIN_CUDA
	SKEPU_EXAMPLE_MILLER_RABIN_MPI
	SKEPU_EXAMPLE_MILLER_RABIN_MPI_CUDA
	SKEPU_EXAMPLE_MILLER_RABIN_OPENCL
	SKEPU_EXAMPLE_MILLER_RABIN_OPENMP)

option(SKEPU_EXAMPLE_MMMULT "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MMMULT_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MMMULT_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MMMULT_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MMMULT_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MMMULT_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MMMULT
	SKEPU_EXAMPLE_MMMULT_CUDA
	SKEPU_EXAMPLE_MMMULT_MPI
	SKEPU_EXAMPLE_MMMULT_MPI_CUDA
	SKEPU_EXAMPLE_MMMULT_OPENCL
	SKEPU_EXAMPLE_MMMULT_OPENMP)

option(SKEPU_EXAMPLE_MMMULT_ROW_COL "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MMMULT_ROW_COL_CUDA "" OFF) # ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MMMULT_ROW_COL_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MMMULT_ROW_COL_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MMMULT_ROW_COL_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MMMULT_ROW_COL_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MMMULT_ROW_COL
	SKEPU_EXAMPLE_MMMULT_ROW_COL_CUDA
	SKEPU_EXAMPLE_MMMULT_ROW_COL_MPI
	SKEPU_EXAMPLE_MMMULT_ROW_COL_MPI_CUDA
	SKEPU_EXAMPLE_MMMULT_ROW_COL_OPENCL
	SKEPU_EXAMPLE_MMMULT_ROW_COL_OPENMP)

option(SKEPU_EXAMPLE_MONTECARLO "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MONTECARLO_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MONTECARLO_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MONTECARLO_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MONTECARLO_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MONTECARLO_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MONTECARLO
	SKEPU_EXAMPLE_MONTECARLO_CUDA
	SKEPU_EXAMPLE_MONTECARLO_MPI
	SKEPU_EXAMPLE_MONTECARLO_MPI_CUDA
	SKEPU_EXAMPLE_MONTECARLO_OPENCL
	SKEPU_EXAMPLE_MONTECARLO_OPENMP)

option(SKEPU_EXAMPLE_MVMULT "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MVMULT_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MVMULT_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MVMULT_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MVMULT_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MVMULT_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MVMULT
	SKEPU_EXAMPLE_MVMULT_CUDA
	SKEPU_EXAMPLE_MVMULT_MPI
	SKEPU_EXAMPLE_MVMULT_MPI_CUDA
	SKEPU_EXAMPLE_MVMULT_OPENCL
	SKEPU_EXAMPLE_MVMULT_OPENMP)

option(SKEPU_EXAMPLE_MVMULT_ROW "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MVMULT_ROW_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MVMULT_ROW_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MVMULT_ROW_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MVMULT_ROW_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MVMULT_ROW_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MVMULT_ROW
	SKEPU_EXAMPLE_MVMULT_ROW_CUDA
	SKEPU_EXAMPLE_MVMULT_ROW_MPI
	SKEPU_EXAMPLE_MVMULT_ROW_MPI_CUDA
	SKEPU_EXAMPLE_MVMULT_ROW_OPENCL
	SKEPU_EXAMPLE_MVMULT_ROW_OPENMP)

option(SKEPU_EXAMPLE_NBODY "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_NBODY_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_NBODY_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_NBODY_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_NBODY_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_NBODY_MPI_CUDA "" ${SKEPU_MPI_CUDA})
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_NBODY
	SKEPU_EXAMPLE_NBODY_CUDA
	SKEPU_EXAMPLE_NBODY_MPI
	SKEPU_EXAMPLE_NBODY_MPI_CUDA
	SKEPU_EXAMPLE_NBODY_OPENCL
	SKEPU_EXAMPLE_NBODY_OPENMP)

option(SKEPU_EXAMPLE_NBODY_MAPPAIRS "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_NBODY_MAPPAIRS_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_NBODY_MAPPAIRS_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_NBODY_MAPPAIRS_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_NBODY_MAPPAIRS_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_NBODY_MAPPAIRS_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_NBODY_MAPPAIRS
	SKEPU_EXAMPLE_NBODY_MAPPAIRS_CUDA
	SKEPU_EXAMPLE_NBODY_MAPPAIRS_MPI
	SKEPU_EXAMPLE_NBODY_MAPPAIRS_MPI_CUDA
	SKEPU_EXAMPLE_NBODY_MAPPAIRS_OPENCL
	SKEPU_EXAMPLE_NBODY_MAPPAIRS_OPENMP)

option(SKEPU_EXAMPLE_NBODY_NOSKEPU "" ${SKEPU_BUILD_EXAMPLES})
mark_as_advanced(FORCE SKEPU_EXAMPLE_NBODY_NOSKEPU)

option(SKEPU_EXAMPLE_PPMCC "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_PPMCC_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_PPMCC_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_PPMCC_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_PPMCC_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_PPMCC_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_PPMCC
	SKEPU_EXAMPLE_PPMCC_CUDA
	SKEPU_EXAMPLE_PPMCC_MPI
	SKEPU_EXAMPLE_PPMCC_MPI_CUDA
	SKEPU_EXAMPLE_PPMCC_OPENCL
	SKEPU_EXAMPLE_PPMCC_OPENMP)

option(SKEPU_EXAMPLE_PSNR "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_PSNR_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_PSNR_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_PSNR_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_PSNR_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_PSNR_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_PSNR
	SKEPU_EXAMPLE_PSNR_CUDA
	SKEPU_EXAMPLE_PSNR_MPI
	SKEPU_EXAMPLE_PSNR_MPI_CUDA
	SKEPU_EXAMPLE_PSNR_OPENCL
	SKEPU_EXAMPLE_PSNR_OPENMP)

option(SKEPU_EXAMPLE_RIEMANN_SUM "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_RIEMANN_SUM_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_RIEMANN_SUM_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_RIEMANN_SUM_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_RIEMANN_SUM_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_RIEMANN_SUM_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_RIEMANN_SUM
	SKEPU_EXAMPLE_RIEMANN_SUM_CUDA
	SKEPU_EXAMPLE_RIEMANN_SUM_MPI
	SKEPU_EXAMPLE_RIEMANN_SUM_MPI_CUDA
	SKEPU_EXAMPLE_RIEMANN_SUM_OPENCL
	SKEPU_EXAMPLE_RIEMANN_SUM_OPENMP)

option(SKEPU_EXAMPLE_TAYLOR "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_TAYLOR_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_TAYLOR_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_TAYLOR_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_TAYLOR_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_TAYLOR_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_TAYLOR
	SKEPU_EXAMPLE_TAYLOR_CUDA
	SKEPU_EXAMPLE_TAYLOR_MPI
	SKEPU_EXAMPLE_TAYLOR_MPI_CUDA
	SKEPU_EXAMPLE_TAYLOR_OPENCL
	SKEPU_EXAMPLE_TAYLOR_OPENMP)
