if(SKEPU_MPI AND SKEPU_CUDA)
	set(SKEPU_MPI_CUDA ON)
else()
	set(SKEPU_MPI_CUDA OFF)
endif()

option(SKEPU_EXAMPLE_BACKENDSPEC "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_BACKENDSPEC_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_BACKENDSPEC_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_BACKENDSPEC_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_BACKENDSPEC_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_BACKENDSPEC_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_BACKENDSPEC
	SKEPU_EXAMPLE_BACKENDSPEC_CUDA
	SKEPU_EXAMPLE_BACKENDSPEC_MPI
	SKEPU_EXAMPLE_BACKENDSPEC_MPI_CUDA
	SKEPU_EXAMPLE_BACKENDSPEC_OPENCL
	SKEPU_EXAMPLE_BACKENDSPEC_OPENMP)

option(SKEPU_EXAMPLE_CALL "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_CALL_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_CALL_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_CALL_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_CALL_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_CALL_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_CALL
	SKEPU_EXAMPLE_CALL_CUDA
	SKEPU_EXAMPLE_CALL_MPI
	SKEPU_EXAMPLE_CALL_MPI_CUDA
	SKEPU_EXAMPLE_CALL_OPENCL
	SKEPU_EXAMPLE_CALL_OPENMP)

option(SKEPU_EXAMPLE_CMA "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_CMA_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_CMA_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_CMA_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_CMA_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_CMA_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_CMA
	SKEPU_EXAMPLE_CMA_CUDA
	SKEPU_EXAMPLE_CMA_MPI
	SKEPU_EXAMPLE_CMA_MPI_CUDA
	SKEPU_EXAMPLE_CMA_OPENCL
	SKEPU_EXAMPLE_CMA_OPENMP)

option(SKEPU_EXAMPLE_COMPLEX "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_COMPLEX_CUDA "" OFF) # ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_COMPLEX_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_COMPLEX_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_COMPLEX_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_COMPLEX_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_COMPLEX
	SKEPU_EXAMPLE_COMPLEX_CUDA
	SKEPU_EXAMPLE_COMPLEX_MPI
	SKEPU_EXAMPLE_COMPLEX_MPI_CUDA
	SKEPU_EXAMPLE_COMPLEX_OPENCL
	SKEPU_EXAMPLE_COMPLEX_OPENMP)

option(SKEPU_EXAMPLE_CONTAINERS "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_CONTAINERS_CUDA "" OFF) # ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_CONTAINERS_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_CONTAINERS_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_CONTAINERS_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_CONTAINERS_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_CONTAINERS
	SKEPU_EXAMPLE_CONTAINERS_CUDA
	SKEPU_EXAMPLE_CONTAINERS_MPI
	SKEPU_EXAMPLE_CONTAINERS_MPI_CUDA
	SKEPU_EXAMPLE_CONTAINERS_OPENCL
	SKEPU_EXAMPLE_CONTAINERS_OPENMP)

option(SKEPU_EXAMPLE_COULOMBIC "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_COULOMBIC_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_COULOMBIC_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_COULOMBIC_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_COULOMBIC_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_COULOMBIC_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_COULOMBIC
	SKEPU_EXAMPLE_COULOMBIC_CUDA
	SKEPU_EXAMPLE_COULOMBIC_MPI
	SKEPU_EXAMPLE_COULOMBIC_MPI_CUDA
	SKEPU_EXAMPLE_COULOMBIC_OPENCL
	SKEPU_EXAMPLE_COULOMBIC_OPENMP)

option(SKEPU_EXAMPLE_DOTPRODUCT "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_DOTPRODUCT_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_DOTPRODUCT_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_DOTPRODUCT_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_DOTPRODUCT_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_DOTPRODUCT_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_DOTPRODUCT
	SKEPU_EXAMPLE_DOTPRODUCT_CUDA
	SKEPU_EXAMPLE_DOTPRODUCT_MPI
	SKEPU_EXAMPLE_DOTPRODUCT_MPI_CUDA
	SKEPU_EXAMPLE_DOTPRODUCT_OPENCL
	SKEPU_EXAMPLE_DOTPRODUCT_OPENMP)

option(SKEPU_EXAMPLE_LAMBDA "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_LAMBDA_CUDA "" OFF) # ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_LAMBDA_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_LAMBDA_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_LAMBDA_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_LAMBDA_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_LAMBDA
	SKEPU_EXAMPLE_LAMBDA_CUDA
	SKEPU_EXAMPLE_LAMBDA_MPI
	SKEPU_EXAMPLE_LAMBDA_MPI_CUDA
	SKEPU_EXAMPLE_LAMBDA_OPENCL
	SKEPU_EXAMPLE_LAMBDA_OPENMP)

option(SKEPU_EXAMPLE_MANDELBROT "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MANDELBROT_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MANDELBROT_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MANDELBROT_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MANDELBROT_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MANDELBROT_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MANDELBROT
	SKEPU_EXAMPLE_MANDELBROT_CUDA
	SKEPU_EXAMPLE_MANDELBROT_MPI
	SKEPU_EXAMPLE_MANDELBROT_MPI_CUDA
	SKEPU_EXAMPLE_MANDELBROT_OPENCL
	SKEPU_EXAMPLE_MANDELBROT_OPENMP)

option(SKEPU_EXAMPLE_MAP "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MAP_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MAP_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MAP_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MAP_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MAP_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MAP
	SKEPU_EXAMPLE_MAP_CUDA
	SKEPU_EXAMPLE_MAP_MPI
	SKEPU_EXAMPLE_MAP_MPI_CUDA
	SKEPU_EXAMPLE_MAP_OPENCL
	SKEPU_EXAMPLE_MAP_OPENMP)

option(SKEPU_EXAMPLE_MAPOVERLAP "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MAPOVERLAP_CUDA "" OFF) # ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MAPOVERLAP_OPENCL "" OFF) #${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MAPOVERLAP_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MAPOVERLAP_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MAPOVERLAP_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MAPOVERLAP
	SKEPU_EXAMPLE_MAPOVERLAP_CUDA
	SKEPU_EXAMPLE_MAPOVERLAP_MPI
	SKEPU_EXAMPLE_MAPOVERLAP_MPI_CUDA
	SKEPU_EXAMPLE_MAPOVERLAP_OPENCL
	SKEPU_EXAMPLE_MAPOVERLAP_OPENMP)

option(SKEPU_EXAMPLE_MAPOVERLAP-TUPLE "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MAPOVERLAP-TUPLE_CUDA "" OFF) # ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MAPOVERLAP-TUPLE_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MAPOVERLAP-TUPLE_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MAPOVERLAP-TUPLE_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MAPOVERLAP-TUPLE_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MAPOVERLAP-TUPLE
	SKEPU_EXAMPLE_MAPOVERLAP-TUPLE_CUDA
	SKEPU_EXAMPLE_MAPOVERLAP-TUPLE_MPI
	SKEPU_EXAMPLE_MAPOVERLAP-TUPLE_MPI_CUDA
	SKEPU_EXAMPLE_MAPOVERLAP-TUPLE_OPENCL
	SKEPU_EXAMPLE_MAPOVERLAP-TUPLE_OPENMP)

option(SKEPU_EXAMPLE_MAPPAIRS "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MAPPAIRS_CUDA "" OFF) # ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MAPPAIRS_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MAPPAIRS_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MAPPAIRS_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MAPPAIRS_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MAPPAIRS
	SKEPU_EXAMPLE_MAPPAIRS_CUDA
	SKEPU_EXAMPLE_MAPPAIRS_MPI
	SKEPU_EXAMPLE_MAPPAIRS_MPI_CUDA
	SKEPU_EXAMPLE_MAPPAIRS_OPENCL
	SKEPU_EXAMPLE_MAPPAIRS_OPENMP)

option(SKEPU_EXAMPLE_MAPPAIRS_TUPLE "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MAPPAIRS_TUPLE_CUDA "" OFF) # ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MAPPAIRS_TUPLE_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MAPPAIRS_TUPLE_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MAPPAIRS_TUPLE_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MAPPAIRS_TUPLE_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MAPPAIRS_TUPLE
	SKEPU_EXAMPLE_MAPPAIRS_TUPLE_CUDA
	SKEPU_EXAMPLE_MAPPAIRS_TUPLE_MPI
	SKEPU_EXAMPLE_MAPPAIRS_TUPLE_MPI_CUDA
	SKEPU_EXAMPLE_MAPPAIRS_TUPLE_OPENCL
	SKEPU_EXAMPLE_MAPPAIRS_TUPLE_OPENMP)

option(SKEPU_EXAMPLE_MAPREDUCE "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MAPREDUCE_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MAPREDUCE_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MAPREDUCE_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MAPREDUCE_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MAPREDUCE_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MAPREDUCE
	SKEPU_EXAMPLE_MAPREDUCE_CUDA
	SKEPU_EXAMPLE_MAPREDUCE_MPI
	SKEPU_EXAMPLE_MAPREDUCE_MPI_CUDA
	SKEPU_EXAMPLE_MAPREDUCE_OPENCL
	SKEPU_EXAMPLE_MAPREDUCE_OPENMP)

option(SKEPU_EXAMPLE_MAPTUPLE "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MAPTUPLE_CUDA "" OFF) # ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MAPTUPLE_OPENCL "" OFF) # ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MAPTUPLE_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MAPTUPLE_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MAPTUPLE_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MAPTUPLE
	SKEPU_EXAMPLE_MAPTUPLE_CUDA
	SKEPU_EXAMPLE_MAPTUPLE_MPI
	SKEPU_EXAMPLE_MAPTUPLE_MPI_CUDA
	SKEPU_EXAMPLE_MAPTUPLE_OPENCL
	SKEPU_EXAMPLE_MAPTUPLE_OPENMP)

option(SKEPU_EXAMPLE_MAXMIN "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MAXMIN_CUDA "" OFF) # ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MAXMIN_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MAXMIN_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MAXMIN_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MAXMIN_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MAXMIN
	SKEPU_EXAMPLE_MAXMIN_CUDA
	SKEPU_EXAMPLE_MAXMIN_MPI
	SKEPU_EXAMPLE_MAXMIN_MPI_CUDA
	SKEPU_EXAMPLE_MAXMIN_OPENCL
	SKEPU_EXAMPLE_MAXMIN_OPENMP)

option(SKEPU_EXAMPLE_MEDIAN "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MEDIAN_CUDA "" OFF) # ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MEDIAN_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MEDIAN_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MEDIAN_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MEDIAN_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MEDIAN
	SKEPU_EXAMPLE_MEDIAN_CUDA
	SKEPU_EXAMPLE_MEDIAN_MPI
	SKEPU_EXAMPLE_MEDIAN_MPI_CUDA
	SKEPU_EXAMPLE_MEDIAN_OPENCL
	SKEPU_EXAMPLE_MEDIAN_OPENMP)

option(SKEPU_EXAMPLE_MMMULT "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MMMULT_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MMMULT_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MMMULT_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MMMULT_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MMMULT_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MMMULT
	SKEPU_EXAMPLE_MMMULT_CUDA
	SKEPU_EXAMPLE_MMMULT_MPI
	SKEPU_EXAMPLE_MMMULT_MPI_CUDA
	SKEPU_EXAMPLE_MMMULT_OPENCL
	SKEPU_EXAMPLE_MMMULT_OPENMP)

option(SKEPU_EXAMPLE_MMMULT_ROW_COL "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MMMULT_ROW_COL_CUDA "" OFF) # ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MMMULT_ROW_COL_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MMMULT_ROW_COL_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MMMULT_ROW_COL_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MMMULT_ROW_COL_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MMMULT_ROW_COL
	SKEPU_EXAMPLE_MMMULT_ROW_COL_CUDA
	SKEPU_EXAMPLE_MMMULT_ROW_COL_MPI
	SKEPU_EXAMPLE_MMMULT_ROW_COL_MPI_CUDA
	SKEPU_EXAMPLE_MMMULT_ROW_COL_OPENCL
	SKEPU_EXAMPLE_MMMULT_ROW_COL_OPENMP)

option(SKEPU_EXAMPLE_MVMULT "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MVMULT_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MVMULT_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MVMULT_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MVMULT_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MVMULT_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MVMULT
	SKEPU_EXAMPLE_MVMULT_CUDA
	SKEPU_EXAMPLE_MVMULT_MPI
	SKEPU_EXAMPLE_MVMULT_MPI_CUDA
	SKEPU_EXAMPLE_MVMULT_OPENCL
	SKEPU_EXAMPLE_MVMULT_OPENMP)

option(SKEPU_EXAMPLE_MVMULT_ROW "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_MVMULT_ROW_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_MVMULT_ROW_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_MVMULT_ROW_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_MVMULT_ROW_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_MVMULT_ROW_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_MVMULT_ROW
	SKEPU_EXAMPLE_MVMULT_ROW_CUDA
	SKEPU_EXAMPLE_MVMULT_ROW_MPI
	SKEPU_EXAMPLE_MVMULT_ROW_MPI_CUDA
	SKEPU_EXAMPLE_MVMULT_ROW_OPENCL
	SKEPU_EXAMPLE_MVMULT_ROW_OPENMP)

option(SKEPU_EXAMPLE_NBODY "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_NBODY_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_NBODY_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_NBODY_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_NBODY_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_NBODY_MPI_CUDA "" ${SKEPU_MPI_CUDA})
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_NBODY
	SKEPU_EXAMPLE_NBODY_CUDA
	SKEPU_EXAMPLE_NBODY_MPI
	SKEPU_EXAMPLE_NBODY_MPI_CUDA
	SKEPU_EXAMPLE_NBODY_OPENCL
	SKEPU_EXAMPLE_NBODY_OPENMP)

option(SKEPU_EXAMPLE_NBODY_MAPPAIRS "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_NBODY_MAPPAIRS_CUDA "" OFF) # ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_NBODY_MAPPAIRS_OPENCL "" OFF) # ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_NBODY_MAPPAIRS_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_NBODY_MAPPAIRS_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_NBODY_MAPPAIRS_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_NBODY_MAPPAIRS
	SKEPU_EXAMPLE_NBODY_MAPPAIRS_CUDA
	SKEPU_EXAMPLE_NBODY_MAPPAIRS_MPI
	SKEPU_EXAMPLE_NBODY_MAPPAIRS_MPI_CUDA
	SKEPU_EXAMPLE_NBODY_MAPPAIRS_OPENCL
	SKEPU_EXAMPLE_NBODY_MAPPAIRS_OPENMP)

option(SKEPU_EXAMPLE_NBODY_NOSKEPU "" ${SKEPU_BUILD_EXAMPLES})
mark_as_advanced(FORCE SKEPU_EXAMPLE_NBODY_NOSKEPU)

option(SKEPU_EXAMPLE_OBJECTORIENTED "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_OBJECTORIENTED_CUDA "" OFF) # ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_OBJECTORIENTED_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_OBJECTORIENTED_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_OBJECTORIENTED_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_OBJECTORIENTED_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_OBJECTORIENTED
	SKEPU_EXAMPLE_OBJECTORIENTED_CUDA
	SKEPU_EXAMPLE_OBJECTORIENTED_MPI
	SKEPU_EXAMPLE_OBJECTORIENTED_MPI_CUDA
	SKEPU_EXAMPLE_OBJECTORIENTED_OPENCL
	SKEPU_EXAMPLE_OBJECTORIENTED_OPENMP)

option(SKEPU_EXAMPLE_PPMCC "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_PPMCC_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_PPMCC_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_PPMCC_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_PPMCC_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_PPMCC_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_PPMCC
	SKEPU_EXAMPLE_PPMCC_CUDA
	SKEPU_EXAMPLE_PPMCC_MPI
	SKEPU_EXAMPLE_PPMCC_MPI_CUDA
	SKEPU_EXAMPLE_PPMCC_OPENCL
	SKEPU_EXAMPLE_PPMCC_OPENMP)

option(SKEPU_EXAMPLE_PSNR "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_PSNR_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_PSNR_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_PSNR_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_PSNR_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_PSNR_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_PSNR
	SKEPU_EXAMPLE_PSNR_CUDA
	SKEPU_EXAMPLE_PSNR_MPI
	SKEPU_EXAMPLE_PSNR_MPI_CUDA
	SKEPU_EXAMPLE_PSNR_OPENCL
	SKEPU_EXAMPLE_PSNR_OPENMP)

option(SKEPU_EXAMPLE_REDUCE "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_REDUCE_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_REDUCE_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_REDUCE_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_REDUCE_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_REDUCE_MPI_CUDA "" ${SKEPU_MPI_CUDA})
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_REDUCE
	SKEPU_EXAMPLE_REDUCE_CUDA
	SKEPU_EXAMPLE_REDUCE_MPI
	SKEPU_EXAMPLE_REDUCE_MPI_CUDA
	SKEPU_EXAMPLE_REDUCE_OPENCL
	SKEPU_EXAMPLE_REDUCE_OPENMP)

option(SKEPU_EXAMPLE_SCAN "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_SCAN_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_SCAN_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_SCAN_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_SCAN_MPI "" ${SKEPU_MPI})
option(SKEPU_EXAMPLE_SCAN_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_SCAN
	SKEPU_EXAMPLE_SCAN_CUDA
	SKEPU_EXAMPLE_SCAN_MPI
	SKEPU_EXAMPLE_SCAN_MPI_CUDA
	SKEPU_EXAMPLE_SCAN_OPENCL
	SKEPU_EXAMPLE_SCAN_OPENMP)

option(SKEPU_EXAMPLE_TAYLOR "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_TAYLOR_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_TAYLOR_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_TAYLOR_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_TAYLOR_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_TAYLOR_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_TAYLOR
	SKEPU_EXAMPLE_TAYLOR_CUDA
	SKEPU_EXAMPLE_TAYLOR_MPI
	SKEPU_EXAMPLE_TAYLOR_MPI_CUDA
	SKEPU_EXAMPLE_TAYLOR_OPENCL
	SKEPU_EXAMPLE_TAYLOR_OPENMP)

option(SKEPU_EXAMPLE_WRITEBACK "" ${SKEPU_BUILD_EXAMPLES})
option(SKEPU_EXAMPLE_WRITEBACK_CUDA "" ${SKEPU_CUDA})
option(SKEPU_EXAMPLE_WRITEBACK_OPENCL "" ${SKEPU_OPENCL})
option(SKEPU_EXAMPLE_WRITEBACK_OPENMP "" ${SKEPU_OPENMP})
option(SKEPU_EXAMPLE_WRITEBACK_MPI "" OFF) # ${SKEPU_MPI})
option(SKEPU_EXAMPLE_WRITEBACK_MPI_CUDA "" OFF)
mark_as_advanced(FORCE
	SKEPU_EXAMPLE_WRITEBACK
	SKEPU_EXAMPLE_WRITEBACK_CUDA
	SKEPU_EXAMPLE_WRITEBACK_MPI
	SKEPU_EXAMPLE_WRITEBACK_MPI_CUDA
	SKEPU_EXAMPLE_WRITEBACK_OPENCL
	SKEPU_EXAMPLE_WRITEBACK_OPENMP)
